
<a name = 'top'></a>

<div class="row">

	<div class="col-6">
		<h3 style="margin-top: 10px">A Brief History of the League</h3>
	</div>

	<div class="col-6">

		<div class="dropdown" style="margin-bottom: 10px">
			
			<button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Years
			</button>
					
			<div class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenuButton">

			{{#sections}}

				<a class='dropdown-item' href='#{{anchor}}'>{{range}}</a>

			{{/sections}}

			</div>

		</div>
	</div>
</div>

{{#sections}}

<a name = '{{anchor}}'>

<h3 style = "margin-top: 10px">{{section_title}}</h3>

<h4>{{range}}</h3>

<div class="row">

	<div class="col-6">

		{{{html}}}

	</div>

	<div class="col-6">

		{{#img}}
		<span class="align-middle">

		<figure class="figure">

			<img class="figure-img img-fluid rounded" src="{{img}}">

			<figcaption class="figure-caption">{{caption}}</figcaption>

		</figure>

		</span>
		{{/img}}

	</div>
</div>

<a href = '#top'>back to top</a>

{{/sections}}
